version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gofmt
    - gosec
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - revive
    - unconvert
    - unused
  exclusions:
    paths:
      - schema.go
      - pulumiManifest.go
