archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-onepassword
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    ldflags:
      # Below line *must* align with the module in the provider/go.mod file.
      - -X github.com/1Password/pulumi-onepassword/provider/pkg/version.Version={{ .Tag }}
    main: ./cmd/pulumi-resource-onepassword/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
