// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword
{
    public static class GetVault
    {
        public static Task<GetVaultResult> InvokeAsync(GetVaultArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVaultResult>("onepassword:index/getVault:getVault", args ?? new GetVaultArgs(), options.WithDefaults());

        public static Output<GetVaultResult> Invoke(GetVaultInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVaultResult>("onepassword:index/getVault:getVault", args ?? new GetVaultInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVaultArgs : global::Pulumi.InvokeArgs
    {
        [Input("name")]
        public string? Name { get; set; }

        [Input("uuid")]
        public string? Uuid { get; set; }

        public GetVaultArgs()
        {
        }
        public static new GetVaultArgs Empty => new GetVaultArgs();
    }

    public sealed class GetVaultInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public GetVaultInvokeArgs()
        {
        }
        public static new GetVaultInvokeArgs Empty => new GetVaultInvokeArgs();
    }


    [OutputType]
    public sealed class GetVaultResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly string Uuid;

        [OutputConstructor]
        private GetVaultResult(
            string description,

            string id,

            string name,

            string uuid)
        {
            Description = description;
            Id = id;
            Name = name;
            Uuid = uuid;
        }
    }
}
