// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class GetItemSectionFileResult
    {
        /// <summary>
        /// The content of the file.
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// The content of the file in base64 encoding. (Use this for binary files.)
        /// </summary>
        public readonly string ContentBase64;
        /// <summary>
        /// The UUID of the file.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the file.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetItemSectionFileResult(
            string content,

            string contentBase64,

            string id,

            string name)
        {
            Content = content;
            ContentBase64 = contentBase64;
            Id = id;
            Name = name;
        }
    }
}
