// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class ItemSectionField
    {
        /// <summary>
        /// A unique identifier for the field.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The label for the field.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// The recipe used to generate a new value for a password.
        /// </summary>
        public readonly Outputs.ItemSectionFieldPasswordRecipe? PasswordRecipe;
        /// <summary>
        /// Purpose indicates this is a special field: a username, password, or notes field. One of ["USERNAME" "PASSWORD" "NOTES"]
        /// </summary>
        public readonly string? Purpose;
        /// <summary>
        /// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// The value of the field.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ItemSectionField(
            string? id,

            string label,

            Outputs.ItemSectionFieldPasswordRecipe? passwordRecipe,

            string? purpose,

            string? type,

            string? value)
        {
            Id = id;
            Label = label;
            PasswordRecipe = passwordRecipe;
            Purpose = purpose;
            Type = type;
            Value = value;
        }
    }
}
