# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_item import *
from .get_vault import *
from .item import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_onepassword.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_onepassword.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "onepassword",
  "mod": "index/item",
  "fqn": "pulumi_onepassword",
  "classes": {
   "onepassword:index/item:Item": "Item"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "onepassword",
  "token": "pulumi:providers:onepassword",
  "fqn": "pulumi_onepassword",
  "class": "Provider"
 }
]
"""
)
