// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetItemSection {
    fields: outputs.GetItemSectionField[];
    id: string;
    label: string;
}

export interface GetItemSectionField {
    id: string;
    label: string;
    purpose: string;
    type: string;
    value: string;
}

export interface ItemPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: boolean;
    /**
     * The length of the password to be generated.
     */
    length?: number;
    /**
     * Use letters [a-zA-Z] when generating the password.
     */
    letters?: boolean;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: boolean;
}

export interface ItemSection {
    /**
     * A list of custom fields in the section.
     */
    fields?: outputs.ItemSectionField[];
    /**
     * A unique identifier for the section.
     */
    id: string;
    /**
     * The label for the section.
     */
    label: string;
}

export interface ItemSectionField {
    /**
     * A unique identifier for the field.
     */
    id: string;
    /**
     * The label for the field.
     */
    label: string;
    /**
     * Password for this item.
     */
    passwordRecipe?: outputs.ItemSectionFieldPasswordRecipe;
    /**
     * Purpose indicates this is a special field: a username, password, or notes field. One of ["USERNAME" "PASSWORD" "NOTES"]
     */
    purpose?: string;
    /**
     * The type of value stored in the field. One of ["STRING" "EMAIL" "CONCEALED" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
     */
    type?: string;
    /**
     * The value of the field.
     */
    value: string;
}

export interface ItemSectionFieldPasswordRecipe {
    /**
     * Use digits [0-9] when generating the password.
     */
    digits?: boolean;
    /**
     * The length of the password to be generated.
     */
    length?: number;
    /**
     * Use letters [a-zA-Z] when generating the password.
     */
    letters?: boolean;
    /**
     * Use symbols [!@.-_*] when generating the password.
     */
    symbols?: boolean;
}

