// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/1Password/pulumi-onepassword/sdk/go/onepassword/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupItem(ctx *pulumi.Context, args *LookupItemArgs, opts ...pulumi.InvokeOption) (*LookupItemResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupItemResult
	err := ctx.Invoke("onepassword:index/getItem:getItem", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getItem.
type LookupItemArgs struct {
	Files     []GetItemFile    `pulumi:"files"`
	NoteValue *string          `pulumi:"noteValue"`
	Sections  []GetItemSection `pulumi:"sections"`
	Title     *string          `pulumi:"title"`
	Uuid      *string          `pulumi:"uuid"`
	Vault     string           `pulumi:"vault"`
}

// A collection of values returned by getItem.
type LookupItemResult struct {
	Category   string           `pulumi:"category"`
	Credential string           `pulumi:"credential"`
	Database   string           `pulumi:"database"`
	Files      []GetItemFile    `pulumi:"files"`
	Hostname   string           `pulumi:"hostname"`
	Id         string           `pulumi:"id"`
	NoteValue  string           `pulumi:"noteValue"`
	Password   string           `pulumi:"password"`
	Port       string           `pulumi:"port"`
	PrivateKey string           `pulumi:"privateKey"`
	PublicKey  string           `pulumi:"publicKey"`
	Sections   []GetItemSection `pulumi:"sections"`
	Tags       []string         `pulumi:"tags"`
	Title      string           `pulumi:"title"`
	Type       string           `pulumi:"type"`
	Url        string           `pulumi:"url"`
	Username   string           `pulumi:"username"`
	Uuid       string           `pulumi:"uuid"`
	Vault      string           `pulumi:"vault"`
}

func LookupItemOutput(ctx *pulumi.Context, args LookupItemOutputArgs, opts ...pulumi.InvokeOption) LookupItemResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupItemResult, error) {
			args := v.(LookupItemArgs)
			r, err := LookupItem(ctx, &args, opts...)
			var s LookupItemResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupItemResultOutput)
}

// A collection of arguments for invoking getItem.
type LookupItemOutputArgs struct {
	Files     GetItemFileArrayInput    `pulumi:"files"`
	NoteValue pulumi.StringPtrInput    `pulumi:"noteValue"`
	Sections  GetItemSectionArrayInput `pulumi:"sections"`
	Title     pulumi.StringPtrInput    `pulumi:"title"`
	Uuid      pulumi.StringPtrInput    `pulumi:"uuid"`
	Vault     pulumi.StringInput       `pulumi:"vault"`
}

func (LookupItemOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupItemArgs)(nil)).Elem()
}

// A collection of values returned by getItem.
type LookupItemResultOutput struct{ *pulumi.OutputState }

func (LookupItemResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupItemResult)(nil)).Elem()
}

func (o LookupItemResultOutput) ToLookupItemResultOutput() LookupItemResultOutput {
	return o
}

func (o LookupItemResultOutput) ToLookupItemResultOutputWithContext(ctx context.Context) LookupItemResultOutput {
	return o
}

func (o LookupItemResultOutput) Category() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Category }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Credential() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Credential }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Database }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Files() GetItemFileArrayOutput {
	return o.ApplyT(func(v LookupItemResult) []GetItemFile { return v.Files }).(GetItemFileArrayOutput)
}

func (o LookupItemResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) NoteValue() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.NoteValue }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Password }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Port() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Port }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) PrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.PrivateKey }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.PublicKey }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Sections() GetItemSectionArrayOutput {
	return o.ApplyT(func(v LookupItemResult) []GetItemSection { return v.Sections }).(GetItemSectionArrayOutput)
}

func (o LookupItemResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupItemResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupItemResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Title }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Url }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Username }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func (o LookupItemResultOutput) Vault() pulumi.StringOutput {
	return o.ApplyT(func(v LookupItemResult) string { return v.Vault }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupItemResultOutput{})
}
