// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/1Password/pulumi-onepassword/sdk/go/onepassword/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVault(ctx *pulumi.Context, args *GetVaultArgs, opts ...pulumi.InvokeOption) (*GetVaultResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVaultResult
	err := ctx.Invoke("onepassword:index/getVault:getVault", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVault.
type GetVaultArgs struct {
	Name *string `pulumi:"name"`
	Uuid *string `pulumi:"uuid"`
}

// A collection of values returned by getVault.
type GetVaultResult struct {
	Description string `pulumi:"description"`
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	Uuid        string `pulumi:"uuid"`
}

func GetVaultOutput(ctx *pulumi.Context, args GetVaultOutputArgs, opts ...pulumi.InvokeOption) GetVaultResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVaultResult, error) {
			args := v.(GetVaultArgs)
			r, err := GetVault(ctx, &args, opts...)
			var s GetVaultResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVaultResultOutput)
}

// A collection of arguments for invoking getVault.
type GetVaultOutputArgs struct {
	Name pulumi.StringPtrInput `pulumi:"name"`
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
}

func (GetVaultOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVaultArgs)(nil)).Elem()
}

// A collection of values returned by getVault.
type GetVaultResultOutput struct{ *pulumi.OutputState }

func (GetVaultResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVaultResult)(nil)).Elem()
}

func (o GetVaultResultOutput) ToGetVaultResultOutput() GetVaultResultOutput {
	return o
}

func (o GetVaultResultOutput) ToGetVaultResultOutputWithContext(ctx context.Context) GetVaultResultOutput {
	return o
}

func (o GetVaultResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetVaultResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o GetVaultResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVaultResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVaultResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetVaultResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetVaultResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetVaultResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVaultResultOutput{})
}
