// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("fields")]
        private List<Inputs.GetItemSectionFieldArgs>? _fields;
        public List<Inputs.GetItemSectionFieldArgs> Fields
        {
            get => _fields ?? (_fields = new List<Inputs.GetItemSectionFieldArgs>());
            set => _fields = value;
        }

        [Input("files")]
        private List<Inputs.GetItemSectionFileArgs>? _files;

        /// <summary>
        /// A list of files attached to the section.
        /// </summary>
        public List<Inputs.GetItemSectionFileArgs> Files
        {
            get => _files ?? (_files = new List<Inputs.GetItemSectionFileArgs>());
            set => _files = value;
        }

        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The label for the section.
        /// </summary>
        [Input("label", required: true)]
        public string Label { get; set; } = null!;

        public GetItemSectionArgs()
        {
        }
        public static new GetItemSectionArgs Empty => new GetItemSectionArgs();
    }
}
