// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionFileInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("content", required: true)]
        private Input<string>? _content;

        /// <summary>
        /// The content of the file.
        /// </summary>
        public Input<string>? Content
        {
            get => _content;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _content = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("contentBase64", required: true)]
        private Input<string>? _contentBase64;

        /// <summary>
        /// The content of the file in base64 encoding. (Use this for binary files.)
        /// </summary>
        public Input<string>? ContentBase64
        {
            get => _contentBase64;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _contentBase64 = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The UUID of the file.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The name of the file.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetItemSectionFileInputArgs()
        {
        }
        public static new GetItemSectionFileInputArgs Empty => new GetItemSectionFileInputArgs();
    }
}
