// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionFieldArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A unique identifier for the field.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The label for the field.
        /// </summary>
        [Input("label", required: true)]
        public string Label { get; set; } = null!;

        /// <summary>
        /// Purpose indicates this is a special field: a username, password, or notes field. One of ["USERNAME" "PASSWORD" "NOTES"]
        /// </summary>
        [Input("purpose", required: true)]
        public string Purpose { get; set; } = null!;

        /// <summary>
        /// The type of value stored in the field. One of ["STRING" "CONCEALED" "EMAIL" "URL" "OTP" "DATE" "MONTH_YEAR" "MENU"]
        /// </summary>
        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        [Input("value", required: true)]
        private string? _value;

        /// <summary>
        /// The value of the field.
        /// </summary>
        public string? Value
        {
            get => _value;
            set => _value = value;
        }

        public GetItemSectionFieldArgs()
        {
        }
        public static new GetItemSectionFieldArgs Empty => new GetItemSectionFieldArgs();
    }
}
