// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("fields")]
        private InputList<Inputs.GetItemSectionFieldInputArgs>? _fields;
        public InputList<Inputs.GetItemSectionFieldInputArgs> Fields
        {
            get => _fields ?? (_fields = new InputList<Inputs.GetItemSectionFieldInputArgs>());
            set => _fields = value;
        }

        [Input("files")]
        private InputList<Inputs.GetItemSectionFileInputArgs>? _files;

        /// <summary>
        /// A list of files attached to the section.
        /// </summary>
        public InputList<Inputs.GetItemSectionFileInputArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.GetItemSectionFileInputArgs>());
            set => _files = value;
        }

        /// <summary>
        /// A unique identifier for the section.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The label for the section.
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        public GetItemSectionInputArgs()
        {
        }
        public static new GetItemSectionInputArgs Empty => new GetItemSectionInputArgs();
    }
}
