// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Inputs
{

    public sealed class GetItemSectionFileArgs : global::Pulumi.InvokeArgs
    {
        [Input("content", required: true)]
        private string? _content;

        /// <summary>
        /// The content of the file.
        /// </summary>
        public string? Content
        {
            get => _content;
            set => _content = value;
        }

        [Input("contentBase64", required: true)]
        private string? _contentBase64;

        /// <summary>
        /// The content of the file in base64 encoding. (Use this for binary files.)
        /// </summary>
        public string? ContentBase64
        {
            get => _contentBase64;
            set => _contentBase64 = value;
        }

        /// <summary>
        /// The UUID of the file.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The name of the file.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetItemSectionFileArgs()
        {
        }
        public static new GetItemSectionFileArgs Empty => new GetItemSectionFileArgs();
    }
}
