name: lint

on:
  workflow_call:
    inputs: {}
  pull_request:
    branches:
      - main
      - v*
      - feature*
    paths-ignore:
      - CHANGELOG.md

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Install go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # The versions of golangci-lint and setup-go here cross-depend and need to update together.
          go-version: 1.25
          # Either this action or golangci-lint needs to disable the cache
          cache: false
      - name: disarm go:embed directives to enable lint
        continue-on-error: true # this fails if there are no go:embed directives
        run: |
          git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'
      - name: prepare upstream
        continue-on-error: true
        run: make upstream
      - run: cd provider && go mod tidy
      - name: golangci-lint
        uses: step-security/golangci-lint-action@2697867e9c204558ca23d0decdd0039dc21f2b93 # v9.3.0
        with:
          working-directory: provider
