name: upgrade_provider

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#45_18_*_*_THU = "At 18:45 (UTC) on Thursday."
    - cron: 45 18 * * THU

jobs:
  upgrade_provider:
    name: upgrade_provider
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
        env:
          GH_TOKEN: ${{ secrets.PULUMI_1P_UPGRADE_PROVIDER_GH_TOKEN }}
