name: upgrade_provider

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#00_07_*_*_MON = "At 07:00 (UTC) on Monday."
    - cron: 00 07 * * MON

permissions:
  contents: read

jobs:
  upgrade_provider:
    name: upgrade_provider
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@12996503de2aaddd72c7426efc43331a8970894f # v0.0.19
        env:
          GH_TOKEN: ${{ secrets.PULUMI_1P_UPGRADE_PROVIDER_GH_TOKEN }}
