// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVault(args?: GetVaultArgs, opts?: pulumi.InvokeOptions): Promise<GetVaultResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("onepassword:index/getVault:getVault", {
        "name": args.name,
        "uuid": args.uuid,
    }, opts);
}

/**
 * A collection of arguments for invoking getVault.
 */
export interface GetVaultArgs {
    name?: string;
    uuid?: string;
}

/**
 * A collection of values returned by getVault.
 */
export interface GetVaultResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly uuid: string;
}
export function getVaultOutput(args?: GetVaultOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetVaultResult> {
    return pulumi.output(args).apply((a: any) => getVault(a, opts))
}

/**
 * A collection of arguments for invoking getVault.
 */
export interface GetVaultOutputArgs {
    name?: pulumi.Input<string>;
    uuid?: pulumi.Input<string>;
}
